### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by makepanic** [alexlafroscia/testdouble-qunit#8]
Hi,
I'm wondering if this addon/package could ship typescript types. It should look something like:

```ts
import { VerificationConfig } from 'testdouble';
declare global {
  interface Assert {
    verify(a: any, check?: VerificationConfig): void;
  }
}
```

Which is what [qunit-dom](https://unpkg.com/qunit-dom@0.8.4/dist/qunit-dom.d.ts) does to extend the qunit assertions with the method signature from [`td.verify`](https://github.com/testdouble/testdouble.js/blob/master/index.d.ts#L265)

I'm unsure where to place them though. The issue is that if one adds it to the ember package, it will work for ember users but not testdouble-qunit users. If one adds it to testdouble-qunit, the types won't work for ember users.

**Comment by alexlafroscia** [comment]
This should be happening already...

https://github.com/alexlafroscia/testdouble-qunit/blob/master/packages/testdouble-qunit/typings/testdouble-qunit.d.ts

Are you using the latest version of the library?

**Comment by makepanic** [comment]
I guess ember-cli-typescript isn't loading them as the test-helper imports from `import 'ember-cli-testdouble-qunit';`

**Comment by alexlafroscia** [comment]
Ahh, that makes sense -- I can add a `typings` to `ember-cli-testdouble-qunit` that applies the `testdouble-qunit` types, I think.

**Comment by alexlafroscia** [comment]
I'm going to close this, as the Ember CLI addon is now "gone". Please install and configure `testdouble-qunit` directly in your application instead!
